# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d6d6c48def4656bf585cfd8d140389bb632a115396f170d6818d5c11df9d885f27b1486912680d1c87902f76d230a9dc92694b252ef5b06f8950bc10ce45a12

test:
  secret_key_base: f4ad64223d5d77dd1f3824e85354ddd5a330a4809ede2015bf029a3bf081e0427d87cb377146e668ea975394cd5f15eda7b420b6eb143bc42d54f9616f1c2a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
